<?php
require __DIR__ . '/bootstrap.php';
$sites = public_sites(12);
render_header('Créez votre espace sur le web', 'Nova CMS permet à chaque développeur de créer son mini-blog, publier ses projets et partager son travail.');
render_nav();
?>
<main>
<section class="platform-hero section-shell">
  <div class="hero-copy"><div class="eyebrow"><span></span> Open source · PHP · Pour les créateurs</div><h1>Votre coin du web.<br><em>Sans usine à gaz.</em></h1><p>Créez un mini-blog personnel, partagez vos projets, écrivez vos notes techniques et gardez le contrôle de vos données.</p><div class="hero-actions"><a class="btn btn-primary" href="<?=e(app_url('register.php'))?>">Créer mon espace <span>→</span></a><a class="btn btn-ghost" href="https://github.com/ephraimlifanjo/cms">Voir le code GitHub</a></div><div class="hero-proof"><span>✓ PHP 8.2+</span><span>✓ MIT License</span><span>✓ MySQL / PostgreSQL / SQLite</span></div></div>
  <div class="hero-art" aria-hidden="true"><img class="hero-art-main" src="<?=e(app_url('assets/images/hero-studio.svg'))?>" alt=""><div class="floating-card floating-one"><b>Publiez.</b><small>Brouillon → live</small></div><div class="floating-card floating-two"><b>Personnalisez.</b><small>Image, couleur, bio</small></div></div>
</section>
<section id="features" class="section-shell feature-strip"><article><span class="feature-icon">01</span><h3>Un compte, un espace</h3><p>Inscription sécurisée, mot de passe hashé et dashboard privé pour chaque créateur.</p></article><article><span class="feature-icon">02</span><h3>Blog + portfolio léger</h3><p>Articles, projets, catégories, images, SEO et une page publique partageable.</p></article><article><span class="feature-icon">03</span><h3>Open source pour de vrai</h3><p>Pas de framework imposé, pas de vendor lock-in : du PHP lisible que les développeurs peuvent forker.</p></article></section>
<section id="creators" class="section-shell creators-section"><div class="section-heading"><div><span class="eyebrow-text">ESPACES RÉCENTS</span><h2>Découvrez ce que les créateurs publient.</h2></div><p>Chaque carte est un mini-site indépendant géré depuis son propre dashboard.</p></div><div class="creator-grid"><?php foreach($sites as $site): ?><a class="creator-card" href="<?=e(app_url('site.php?slug=' . rawurlencode($site['slug'])))?>"><div class="creator-cover"><img src="<?=e(safe_asset_url($site['cover_image'], 'assets/images/cover-creative.svg'))?>" alt=""><span class="article-count"><?=(int)$site['article_count']?> publication<?=(int)$site['article_count']===1?'':'s'?></span></div><div class="creator-meta"><img class="creator-avatar" src="<?=e(safe_asset_url($site['avatar'], 'assets/images/avatar-default.svg'))?>" alt=""><div><h3><?=e($site['name'])?></h3><p><?=e($site['tagline'] ?: 'Un espace propulsé par Nova CMS')?></p><small>@<?=e($site['slug'])?></small></div></div></a><?php endforeach; ?></div></section>
<section class="section-shell open-source-banner"><div><span class="eyebrow-text">NOVA STUDIO COMMUNITY</span><h2>Forkez-le. Améliorez-le. Faites-en votre CMS.</h2><p>Le repository contient le code, les images SVG, les migrations, la CI, la documentation de sécurité et les guides de déploiement.</p></div><a class="btn btn-dark" href="https://github.com/ephraimlifanjo/cms">github.com/ephraimlifanjo/cms ↗</a></section>
</main><?php render_footer(); ?>
