<script lang="ts">let { data } = $props();</script>
<svelte:head><title>Nova Studio Community — Nova CMS</title></svelte:head>

<main class="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24">
  <div class="grid gap-12 lg:grid-cols-[280px_1fr]">
    <aside><div class="text-xs font-black uppercase tracking-[.15em] text-[#635bff]">Nova Studio</div><h1 class="mt-3 text-5xl font-black tracking-[-.055em]">Community</h1><p class="mt-4 text-sm leading-7 text-black/50">Parler projets, code, entraide et opportunités sans feed algorithmique.</p><a href="/community/new" class="mt-7 inline-flex rounded-full bg-black px-5 py-3 text-sm font-black text-white">+ Nouvelle discussion</a><div class="mt-9 grid gap-2"><a href="/community" class="rounded-2xl px-4 py-3 text-sm font-bold {data.channel === '' ? 'bg-white' : ''}">Tout</a>{#each data.channels as channel}<a href="/community?channel={channel.id}" class="rounded-2xl px-4 py-3 text-sm font-bold {data.channel === channel.id ? 'bg-white' : ''}"><span class="text-black/35">#</span> {channel.label}</a>{/each}</div></aside>
    <section><div class="flex items-end justify-between gap-5 border-b border-black/10 pb-6"><div><div class="text-xs font-black uppercase tracking-[.14em] text-black/35">Latest conversations</div><h2 class="mt-2 text-3xl font-black tracking-[-.04em]">What people are talking about.</h2></div></div><div class="divide-y divide-black/10">{#each data.threads as thread}<a href="/community/{thread.id}" class="grid gap-4 py-7 transition hover:pl-2 md:grid-cols-[1fr_auto]"><div><div class="text-[11px] font-black uppercase tracking-[.14em] text-[#635bff]">#{thread.channel_id}</div><h3 class="mt-2 text-2xl font-black tracking-[-.035em]">{thread.title}</h3><p class="mt-2 line-clamp-2 max-w-3xl text-sm leading-6 text-black/50">{thread.body}</p><div class="mt-3 text-xs font-bold text-black/35">{thread.author?.display_name || 'member'} · {thread.replies?.[0]?.count || 0} réponses</div></div><span class="text-black/30">↗</span></a>{:else}<div class="py-16 text-center text-black/45">Aucune discussion dans ce channel.</div>{/each}</div></section>
  </div>
</main>
